### PR TITLE
Remove panic (fixes #395)

### LINKED ISSUE #395: hpack encode_side_update panic: "value out of range"
A curious thing happened, 2 panics from the same server, same process, within a second. Both related to the h2 crate:

**Aug 17, 2019 3:33:15 PM UTC**

```
OS Version: Linux 4.18.0-21-generic (None)
Report Version: 104


Application Specific Information:
value out of range

Thread 0
0   h2                              0xc27b4e            h2::hpack::encoder::encode_int (encoder.rs:381)
1   h2                              0xc25cb1            [inlined] h2::hpack::encoder::encode_size_update (encoder.rs:260)
2   h2                              0xc25cb1            [inlined] h2::hpack::encoder::Encoder::encode_size_updates (encoder.rs:161)
3   h2                              0xc25cb1            h2::hpack::encoder::Encoder::encode (encoder.rs:85)
4   h2                              0xc1e4e3            [inlined] h2::frame::headers::EncodingHeaderBlock::encode (headers.rs:551)
5   h2                              0xc1e4e3            h2::frame::headers::Headers::encode (headers.rs:267)
6   h2                              0x42ed62            h2::codec::framed_write::FramedWrite<T>::buffer (framed_write.rs:128)
7   h2                              0x56811f            [inlined] h2::codec::Codec<T>::buffer (mod.rs:149)
8   h2                              0x56811f            [inlined] h2::proto::streams::prioritize::Prioritize::poll_complete (prioritize.rs:516)
9   h2                              0x56811f            h2::proto::streams::send::Send::poll_complete (send.rs:242)
10  h2                              0x4d7e8e            h2::proto::streams::streams::Streams<T>::poll_complete (streams.rs:595)
11  h2                              0x4819f6            h2::proto::connection::Connection<T>::poll (connection.rs:211)
12  h2                              0x4a1dc0            [inlined] h2::server::Connection<T>::poll_close (server.rs:424)
13  h2                              0x4a1dc0            <h2::server::Connection<T> as futures::stream::Stream>::poll (server.rs:487)
14  hyper                           0x44f518            [inlined] hyper::proto::h2::server::Serving<T>::poll_server (server.rs:164)
15  hyper                           0x44f518            [inlined] <hyper::proto::h2::server::Server<T> as futures::future::Future>::poll (server.rs:106)
16  futures                         0x44f518            <futures::future::either::Either<T> as futures::future::Future>::poll (either.rs:36)
17  futures                         0x5c18e0            [inlined] futures::future::option::<T>::poll (option.rs:12)
18  hyper                           0x5c18e0            <hyper::server::conn::Connection<T> as futures::future::Future>::poll (conn.rs:636)
19  fly_proxy                       0x4add87            [inlined] <fly_proxy::session::http::HttpSession as futures::future::Future>::poll (mod.rs:65)
20  fly_proxy                       0x4add87            <fly_proxy::session::Session as futures::future::Future>::poll (mod.rs:96)
21  fly_proxy                       0x5cb655            [inlined] <fly_proxy::dispatch::Machine as fly_proxy::dispatch::PollMachine>::poll_driving_session (mod.rs:185)
22  core                            0x5cb655            [inlined] core::ops::function::FnOnce::call_once (function.rs:231)
23  rent_to_own                     0x5cb655            [inlined] rent_to_own::RentToOwn<T>::with (lib.rs:179)
24  fly_proxy                       0x5cb655            [inlined] <fly_proxy::dispatch::MachineFuture as futures::future::Future>::poll (mod.rs:89)
25  fly_proxy                       0x5cb655            <fly_proxy::dispatch::DispatchFuture as futures::future::Future>::poll (mod.rs:85)
26  fly_proxy                       0x428ff6            [inlined] <fly_proxy::frontend::tls::Machine as fly_proxy::frontend::tls::PollMachine>::poll_dispatch (tls.rs:159)
27  fly_proxy                       0x428ff6            [inlined] <fly_proxy::frontend::tls::MachineFuture as futures::future::Future>::poll::{{closure}}::{{closure}} (tls.rs:74)
28  rent_to_own                     0x428ff6            [inlined] rent_to_own::RentToOwn<T>::with (lib.rs:179)
29  fly_proxy                       0x428ff6            [inlined] <fly_proxy::frontend::tls::MachineFuture as futures::future::Future>::poll::{{closure}} (tls.rs:74)
30  rent_to_own                     0x428ff6            rent_to_own::RentToOwn<T>::with (lib.rs:179)
31  fly_proxy                       0x50e143            [inlined] <fly_proxy::frontend::tls::MachineFuture as futures::future::Future>::poll (tls.rs:74)
32  fly_proxy                       0x50e143            <fly_proxy::frontend::tls::TlsHandlerFuture as futures::future::Future>::poll (tls.rs:70)
33  fly_proxy                       0x598440            <fly_proxy::runtime::Temporary<T> as futures::future::Future>::poll (runtime.rs:218)
34  alloc                           0xbfcb92            [inlined] <alloc::boxed::Box<T> as futures::future::Future>::poll (mod.rs:113)
35  futures                         0xbfcb92            [inlined] futures::task_impl::Spawn<T>::poll_future_notify::{{closure}} (mod.rs:329)
36  futures                         0xbfcb92            [inlined] futures::task_impl::Spawn<T>::enter::{{closure}} (mod.rs:399)
37  futures                         0xbfcb92            futures::task_impl::std::set (mod.rs:83)
38  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::enter (mod.rs:399)
39  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::poll_fn_notify (mod.rs:291)
40  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::poll_future_notify (mod.rs:329)
41  tokio_threadpool                0xbfc722            [inlined] tokio_threadpool::task::Task::run::{{closure}} (mod.rs:145)
42  core                            0xbfc722            [inlined] core::ops::function::FnOnce::call_once (function.rs:231)
43  std                             0xbfc722            [inlined] <std::panic::AssertUnwindSafe<T> as core::ops::function::FnOnce<T>>::call_once (panic.rs:315)
44  std                             0xbfc722            std::panicking::try::do_call (panicking.rs:293)
45  <unknown>                       0xdce5ea            __rust_maybe_catch_panic (lib.rs:85)
46  std                             0xbf9db9            [inlined] std::panicking::try (panicking.rs:272)
47  std                             0xbf9db9            [inlined] std::panic::catch_unwind (panic.rs:394)
48  tokio_threadpool                0xbf9db9            tokio_threadpool::task::Task::run (mod.rs:130)
49  tokio_threadpool                0xbf3805            [inlined] tokio_threadpool::worker::Worker::run_task2 (mod.rs:567)
50  tokio_threadpool                0xbf3805            tokio_threadpool::worker::Worker::run_task (mod.rs:459)
51  tokio_threadpool                0xbf2ee9            [inlined] tokio_threadpool::worker::Worker::try_steal_task (mod.rs:416)
52  tokio_threadpool                0xbf2ee9            [inlined] tokio_threadpool::worker::Worker::try_run_task (mod.rs:301)
53  tokio_threadpool                0xbf2ee9            tokio_threadpool::worker::Worker::run (mod.rs:241)
54  tokio                           0xbcf11e            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}} (builder.rs:390)
55  tokio_timer                     0xbcf11e            [inlined] tokio_timer::timer::handle::with_default::{{closure}} (handle.rs:101)
56  std                             0xbcf11e            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
57  std                             0xbcf11e            std::thread::local::LocalKey<T>::with (local.rs:245)
58  tokio_timer                     0xbcefdf            [inlined] tokio_timer::timer::handle::with_default (handle.rs:84)
59  tokio                           0xbcefdf            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}} (builder.rs:382)
60  tokio_timer                     0xbcefdf            [inlined] tokio_timer::clock::clock::with_default::{{closure}} (clock.rs:137)
61  std                             0xbcefdf            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
62  std                             0xbcefdf            std::thread::local::LocalKey<T>::with (local.rs:245)
63  tokio_timer                     0xbcf30b            [inlined] tokio_timer::clock::clock::with_default (clock.rs:117)
64  tokio                           0xbcf30b            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}} (builder.rs:381)
65  tokio_reactor                   0xbcf30b            [inlined] tokio_reactor::with_default::{{closure}} (lib.rs:237)
66  std                             0xbcf30b            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
67  std                             0xbcf30b            std::thread::local::LocalKey<T>::with (local.rs:245)
68  tokio_reactor                   0xbd090e            [inlined] tokio_reactor::with_default (lib.rs:217)
69  tokio                           0xbd090e            tokio::runtime::threadpool::builder::Builder::build::{{closure}} (builder.rs:380)
70  tokio_threadpool                0xbfd593            [inlined] tokio_threadpool::callback::Callback::call (callback.rs:22)
71  tokio_threadpool                0xbfd593            [inlined] tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}} (mod.rs:127)
72  tokio_executor                  0xbfd593            [inlined] tokio_executor::global::with_default::{{closure}} (global.rs:209)
73  std                             0xbfd593            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
74  std                             0xbfd593            std::thread::local::LocalKey<T>::with (local.rs:245)
75  tokio_executor                  0xbfd36e            [inlined] tokio_executor::global::with_default (global.rs:178)
76  tokio_threadpool                0xbfd36e            [inlined] tokio_threadpool::worker::Worker::do_run::{{closure}} (mod.rs:125)
77  std                             0xbfd36e            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
78  std                             0xbfd36e            std::thread::local::LocalKey<T>::with (local.rs:245)
79  tokio_threadpool                0xbf53e1            [inlined] tokio_threadpool::worker::Worker::do_run (mod.rs:116)
80  tokio_threadpool                0xbf53e1            [inlined] tokio_threadpool::pool::Pool::spawn_thread::{{closure}} (mod.rs:344)
81  std                             0xbf53e1            std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:136)
82  std                             0xbfc67c            [inlined] std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:470)
83  std                             0xbfc67c            [inlined] <std::panic::AssertUnwindSafe<T> as core::ops::function::FnOnce<T>>::call_once (panic.rs:315)
84  std                             0xbfc67c            std::panicking::try::do_call (panicking.rs:293)
85  <unknown>                       0xdce5ea            __rust_maybe_catch_panic (lib.rs:85)
86  std                             0xbf5ed0            [inlined] std::panicking::try (panicking.rs:272)
87  std                             0xbf5ed0            [inlined] std::panic::catch_unwind (panic.rs:394)
88  std                             0xbf5ed0            [inlined] std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:469)
89  core                            0xbf5ed0            core::ops::function::FnOnce::call_once{{vtable.shim}} (function.rs:231)
90  alloc                           0xdb513f            <alloc::boxed::Box<T> as core::ops::function::FnOnce<T>>::call_once (boxed.rs:704)
91  alloc                           0xdcdc40            [inlined] <alloc::boxed::Box<T> as core::ops::function::FnOnce<T>>::call_once (boxed.rs:704)
92  std                             0xdcdc40            [inlined] std::sys_common::thread::start_thread (thread.rs:13)
93  std                             0xdcdc40            std::sys::unix::thread::Thread::new::thread_start (thread.rs:79)
```

**Aug 17, 2019 3:33:16 PM UTC**

```
OS Version: Linux 4.18.0-21-generic (None)
Report Version: 104


Application Specific Information:
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

Thread 0
0   core                            0x60bf14            core::result::unwrap_failed (macros.rs:18)
1   core                            0x4d4380            [inlined] core::result::Result<T>::unwrap (result.rs:800)
2   h2                              0x4d4380            h2::proto::streams::streams::StreamRef<T>::reserve_capacity (streams.rs:953)
3   h2                              0x5e5f7d            [inlined] h2::share::SendStream<T>::reserve_capacity (share.rs:287)
4   hyper                           0x5e5f7d            <hyper::proto::h2::PipeToSendStream<T> as futures::future::Future>::poll (mod.rs:122)
5   hyper                           0x453d61            [inlined] hyper::proto::h2::server::H2Stream<T>::poll2 (server.rs:290)
6   hyper                           0x453d61            <hyper::proto::h2::server::H2Stream<T> as futures::future::Future>::poll (server.rs:308)
7   alloc                           0xbfcb92            [inlined] <alloc::boxed::Box<T> as futures::future::Future>::poll (mod.rs:113)
8   futures                         0xbfcb92            [inlined] futures::task_impl::Spawn<T>::poll_future_notify::{{closure}} (mod.rs:329)
9   futures                         0xbfcb92            [inlined] futures::task_impl::Spawn<T>::enter::{{closure}} (mod.rs:399)
10  futures                         0xbfcb92            futures::task_impl::std::set (mod.rs:83)
11  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::enter (mod.rs:399)
12  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::poll_fn_notify (mod.rs:291)
13  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::poll_future_notify (mod.rs:329)
14  tokio_threadpool                0xbfc722            [inlined] tokio_threadpool::task::Task::run::{{closure}} (mod.rs:145)
15  core                            0xbfc722            [inlined] core::ops::function::FnOnce::call_once (function.rs:231)
16  std                             0xbfc722            [inlined] <std::panic::AssertUnwindSafe<T> as core::ops::function::FnOnce<T>>::call_once (panic.rs:315)
17  std                             0xbfc722            std::panicking::try::do_call (panicking.rs:293)
18  <unknown>                       0xdce5ea            __rust_maybe_catch_panic (lib.rs:85)
19  std                             0xbf9db9            [inlined] std::panicking::try (panicking.rs:272)
20  std                             0xbf9db9            [inlined] std::panic::catch_unwind (panic.rs:394)
21  tokio_threadpool                0xbf9db9            tokio_threadpool::task::Task::run (mod.rs:130)
22  tokio_threadpool                0xbf3805            [inlined] tokio_threadpool::worker::Worker::run_task2 (mod.rs:567)
23  tokio_threadpool                0xbf3805            tokio_threadpool::worker::Worker::run_task (mod.rs:459)
24  tokio_threadpool                0xbf2ee9            [inlined] tokio_threadpool::worker::Worker::try_steal_task (mod.rs:416)
25  tokio_threadpool                0xbf2ee9            [inlined] tokio_threadpool::worker::Worker::try_run_task (mod.rs:301)
26  tokio_threadpool                0xbf2ee9            tokio_threadpool::worker::Worker::run (mod.rs:241)
27  tokio                           0xbcf11e            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}} (builder.rs:390)
28  tokio_timer                     0xbcf11e            [inlined] tokio_timer::timer::handle::with_default::{{closure}} (handle.rs:101)
29  std                             0xbcf11e            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
30  std                             0xbcf11e            std::thread::local::LocalKey<T>::with (local.rs:245)
31  tokio_timer                     0xbcefdf            [inlined] tokio_timer::timer::handle::with_default (handle.rs:84)
32  tokio                           0xbcefdf            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}} (builder.rs:382)
33  tokio_timer                     0xbcefdf            [inlined] tokio_timer::clock::clock::with_default::{{closure}} (clock.rs:137)
34  std                             0xbcefdf            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
35  std                             0xbcefdf            std::thread::local::LocalKey<T>::with (local.rs:245)
36  tokio_timer                     0xbcf30b            [inlined] tokio_timer::clock::clock::with_default (clock.rs:117)
37  tokio                           0xbcf30b            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}} (builder.rs:381)
38  tokio_reactor                   0xbcf30b            [inlined] tokio_reactor::with_default::{{closure}} (lib.rs:237)
39  std                             0xbcf30b            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
40  std                             0xbcf30b            std::thread::local::LocalKey<T>::with (local.rs:245)
41  tokio_reactor                   0xbd090e            [inlined] tokio_reactor::with_default (lib.rs:217)
42  tokio                           0xbd090e            tokio::runtime::threadpool::builder::Builder::build::{{closure}} (builder.rs:380)
43  tokio_threadpool                0xbfd593            [inlined] tokio_threadpool::callback::Callback::call (callback.rs:22)
44  tokio_threadpool                0xbfd593            [inlined] tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}} (mod.rs:127)
45  tokio_executor                  0xbfd593            [inlined] tokio_executor::global::with_default::{{closure}} (global.rs:209)
46  std                             0xbfd593            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
47  std                             0xbfd593            std::thread::local::LocalKey<T>::with (local.rs:245)
48  tokio_executor                  0xbfd36e            [inlined] tokio_executor::global::with_default (global.rs:178)
49  tokio_threadpool                0xbfd36e            [inlined] tokio_threadpool::worker::Worker::do_run::{{closure}} (mod.rs:125)
50  std                             0xbfd36e            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
51  std                             0xbfd36e            std::thread::local::LocalKey<T>::with (local.rs:245)
52  tokio_threadpool                0xbf53e1            [inlined] tokio_threadpool::worker::Worker::do_run (mod.rs:116)
53  tokio_threadpool                0xbf53e1            [inlined] tokio_threadpool::pool::Pool::spawn_thread::{{closure}} (mod.rs:344)
54  std                             0xbf53e1            std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:136)
55  std                             0xbfc67c            [inlined] std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:470)
56  std                             0xbfc67c            [inlined] <std::panic::AssertUnwindSafe<T> as core::ops::function::FnOnce<T>>::call_once (panic.rs:315)
57  std                             0xbfc67c            std::panicking::try::do_call (panicking.rs:293)
58  <unknown>                       0xdce5ea            __rust_maybe_catch_panic (lib.rs:85)
59  std                             0xbf5ed0            [inlined] std::panicking::try (panicking.rs:272)
60  std                             0xbf5ed0            [inlined] std::panic::catch_unwind (panic.rs:394)
61  std                             0xbf5ed0            [inlined] std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:469)
62  core                            0xbf5ed0            core::ops::function::FnOnce::call_once{{vtable.shim}} (function.rs:231)
63  alloc                           0xdb513f            <alloc::boxed::Box<T> as core::ops::function::FnOnce<T>>::call_once (boxed.rs:704)
64  alloc                           0xdcdc40            [inlined] <alloc::boxed::Box<T> as core::ops::function::FnOnce<T>>::call_once (boxed.rs:704)
65  std                             0xdcdc40            [inlined] std::sys_common::thread::start_thread (thread.rs:13)
66  std                             0xdcdc40            std::sys::unix::thread::Thread::new::thread_start (thread.rs:79)
```

Running rust 1.36.0.

This only happened once, and we're serving a lot of requests. Still could be interesting to fix it though (if possible). Not panicking would probably be good if it's unfixable.

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

File: src/hpack/encoder.rs [hunk 1]
```diff
@@ -384,10 +384,6 @@ fn encode_int<B: BufMut>(
 
     value -= low;
 
-    if value > 0x0fff_ffff {
```
Comment (seanmonstar) [inline src/hpack/encoder.rs:387]: I feel like this is probably here for a reason... But I don't know what it is. At the least, I'd like to make sure the spec doesn't describe some upper limit that was being protected for here...

Comment (nox) [reply src/hpack/encoder.rs:387]: I didn't find any limit in either HTTP/2 or HPACK, but I will check again.

Comment (nox) [reply src/hpack/encoder.rs:387]: I checked a few other implementations:

[`hpack-rs`](https://github.com/mlalic/hpack-rs/blob/e833ecac324fb9457e04737f482328c3b5cc93fa/src/encoder.rs#L53-L120) doesn't have that hard limit.
[`httlib-hpack`](https://github.com/xpepermint/httlib-rs/blob/e733390c52fdc2d784864507877416705480db97/hpack/src/encoder/primitives.rs#L3-L70) also doesn't have that hard limit.
[`tokio-http2`](https://github.com/lambdastackio/tokio-http2/blob/fad8751ada3568d8cf4890d6f39ab3ee7d7c7301/src/hpack/encoder.rs#L53-L120) does the same as `hpack-rs`.
[`hpack-codec`](https://github.com/sile/hpack_codec/blob/cfc49c78d16dc38d9529ed20a380355d9c4c34ba/src/literal.rs#L11-L33) only supports encoding `u16` values.

Between this and our chat yesterday on Discord, IMO we should just merge this PR.

**Review by seanmonstar — APPROVED** [review]
