### PR TITLE
fix: pending-accept remotely-reset streams pattern was checking is_local

### LINKED ISSUE #674: Panicking following 0.3.17
It would seem that the patch brought forth some issues.

We panic at https://github.com/hyperium/h2/blob/af4bcacf6d3770e9e3dc10fdc631fc8c0bdd472b/src/proto/streams/streams.rs#L146, causing us to panic again at https://github.com/hyperium/h2/blob/master/src/proto/streams/streams.rs#L1359.

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #674

### CODE REVIEW

**Review by Noah-Kennedy — APPROVED** [review]

**Review by arazmj — APPROVED** [review]

File: src/proto/streams/state.rs [hunk 1]
```diff
@@ -362,7 +362,8 @@ impl State {
 
     pub fn is_remote_reset(&self) -> bool {
         match self.inner {
-            Closed(Cause::Error(ref e)) => e.is_local(),
+            // SEAN: WAT
```
Comment (LucioFranco) [inline src/proto/streams/state.rs:365]: left over?

Comment (seanmonstar) [reply src/proto/streams/state.rs:365]: lol yes

Comment (Noah-Kennedy) [reply src/proto/streams/state.rs]: probably, but it adds flavor to the code :joy:
